// Exportar todas las interfaces de repositorios
export type { IRepository } from "./IRepository";
export type { IUserRepository } from "./IUserRepository";
export type { ITournamentRepository } from "./ITournamentRepository";
export type { ITeamRepository } from "./ITeamRepository";
export type { IPlayerRepository } from "./IPlayerRepository";
export type { IGameRepository } from "./IGameRepository";
export type { IStandingRepository } from "./IStandingRepository";
export type { IDivisionRepository } from "./IDivisionRepository";
