"use client";
import type { CommerceItemDto, CommerceOrderDto } from "@lufa/contracts";
import { FormEvent, useCallback, useEffect, useState } from "react";
import styles from "./seller.module.css";
type Seller = { id: string; slug: string; name: string };
const money = (minor: number) => new Intl.NumberFormat("es-UY", { style: "currency", currency: "UYU" }).format(minor / 100);
async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { cache: "no-store", ...init, headers: { "Content-Type": "application/json", ...init?.headers } }); const body = await response.json(); if (!response.ok) throw new Error(body.message); return body.data; }
export function SellerWorkspace() {
  const [sellers,setSellers]=useState<Seller[]>([]),[items,setItems]=useState<CommerceItemDto[]>([]),[orders,setOrders]=useState<CommerceOrderDto[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{const [s,i,o]=await Promise.all([api<Seller[]>("/api/commerce/seller/profile"),api<CommerceItemDto[]>("/api/commerce/seller/items"),api<CommerceOrderDto[]>("/api/commerce/seller/orders")]);setSellers(s);setItems(i);setOrders(o);}catch(e){setError(e instanceof Error?e.message:"No pudimos abrir el portal.");}},[]); useEffect(()=>{void load();},[load]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const formElement=event.currentTarget;const form=new FormData(formElement);try{await api("/api/commerce/seller/items",{method:"POST",body:JSON.stringify({sellerId:form.get("sellerId"),slug:form.get("slug"),kind:form.get("kind"),title:form.get("title"),description:form.get("description"),priceMinor:Math.round(Number(form.get("price"))*100),credentialDiscountBps:Math.round(Number(form.get("discount"))*100),stockQuantity:form.get("stock")?Number(form.get("stock")):null,active:true})});formElement.reset();await load();}catch(e){setError(e instanceof Error?e.message:"No pudimos publicar.");}finally{setBusy(false);}}
  async function toggle(item:CommerceItemDto){try{await api(`/api/commerce/seller/items/${item.id}`,{method:"PATCH",body:JSON.stringify({active:!item.active})});await load();}catch(e){setError(e instanceof Error?e.message:"No pudimos actualizar.");}}
  async function refund(order:CommerceOrderDto){const reason=window.prompt("Motivo del reembolso propuesto");if(!reason)return;try{await api(`/api/commerce/seller/orders/${order.id}/refund-requests`,{method:"POST",body:JSON.stringify({amountMinor:order.totalMinor,reason})});setError("Solicitud enviada a LUFA para aprobación.");}catch(e){setError(e instanceof Error?e.message:"No pudimos solicitar el reembolso.");}}
  if(error&&sellers.length===0)return <p className={styles.notice}>{error} Iniciá sesión con una cuenta habilitada por LUFA.</p>;
  return <div className={styles.workspace}><section><h2>Publicar artículo</h2><form onSubmit={create}><label>Vendedor<select name="sellerId" required>{sellers.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Tipo<select name="kind"><option value="product">Producto</option><option value="service">Servicio o curso</option></select></label><label>Título<input name="title" required/></label><label>Slug<input name="slug" pattern="[a-z0-9-]+" placeholder="pelota-wilson" required/></label><label className={styles.wide}>Descripción<textarea name="description" required/></label><label>Precio UYU<input name="price" type="number" min="1" step="0.01" required/></label><label>Descuento Mi ID (%)<input name="discount" type="number" min="0" max="90" defaultValue="0"/></label><label>Stock (vacío = ilimitado)<input name="stock" type="number" min="0"/></label><button disabled={busy||!sellers.length}>{busy?"Publicando…":"Publicar"}</button></form></section><section><h2>Mi catálogo</h2><div className={styles.rows}>{items.map(item=><article key={item.id}><div><small>{item.seller.name} · {item.kind}</small><strong>{item.title}</strong><span>{money(item.priceMinor)} · Stock {item.stockQuantity??"ilimitado"}</span></div><button onClick={()=>toggle(item)}>{item.active?"Ocultar":"Publicar"}</button></article>)}</div></section><section className={styles.orders}><h2>Últimas ventas</h2><div className={styles.rows}>{orders.map(order=><article key={order.id}><div><small>{order.createdAt.slice(0,10)} · {order.status}</small><strong>{order.items.map(i=>i.title).join(", ")}</strong><span>{money(order.totalMinor)}</span></div>{order.status==="paid"?<button onClick={()=>refund(order)}>Solicitar reembolso</button>:null}</article>)}</div></section>{error?<p className={styles.notice}>{error}</p>:null}</div>;
}
